### ISSUE TITLE
Unable to configure config file. 

### ISSUE THREAD

**Issue by madvtak** [ninthwalker/NowShowing#40] opened 2017-09-06 05:11 UTC
Hi,

I have this installed on my synology running docker. After I added all the variables listed, and go to localhost:6878

I see this
Default NowShowing Page
This will be replaced after you run your first report

How do I force the first report?

**Comment by ninthwalker** [comment] 2017-09-06 05:22
Please see the command line options page of the Wiki if you want to manually run it without scheduling it with cron in the advanced.yaml 

https://github.com/ninthwalker/NowShowing/wiki/Command-Line-Options

**Comment by madvtak** [comment] 2017-09-06 14:47
When i do that i get no configuration file found. This is what docker shows. Am i missing anything else? I have everything filled out i just deleted for the screenshot. 

![docker](https://user-images.githubusercontent.com/18261123/30118315-91a9c68c-92d7-11e7-969f-ae5f9d0c7863.png)

**Comment by markhaines** [comment] 2017-09-06 14:50
I'm running it on Synology too.  Have you shared a directory, given it RW access and placed the config there?
<img width="590" alt="ds2 nas" src="https://user-images.githubusercontent.com/1022008/30118494-13fd2dac-931b-11e7-908c-ddbba9320c1b.png">

**Comment by madvtak** [comment] 2017-09-06 14:57
yes

![image](https://user-images.githubusercontent.com/18261123/30118898-08ba545c-92d9-11e7-8444-1f39eb33821d.png)

**Comment by markhaines** [comment] 2017-09-06 14:59
This is what my config folder looks like if thats any help to compare:

<img width="845" alt="ds2 nas" src="https://user-images.githubusercontent.com/1022008/30118982-58680cea-931c-11e7-85c8-31a8b4a1a5f9.png">

**Comment by madvtak** [comment] 2017-09-06 15:05
im so happy someone is responding so fast. Let me change my folder name from ninthwalker to nowshowing to see if it makes a difference

**Comment by madvtak** [comment] 2017-09-06 15:11
![image](https://user-images.githubusercontent.com/18261123/30119494-c27bd388-92da-11e7-8b59-d3696d9f263f.png)

This is when im getting when i tjry to run a nowshowing web report
![image](https://user-images.githubusercontent.com/18261123/30119510-d5937552-92da-11e7-824d-a8f868dccf06.png)

**Comment by madvtak** [comment] 2017-09-06 15:13
Also, this is what i see when i go to localhost:port
![image](https://user-images.githubusercontent.com/18261123/30119625-30f88df6-92db-11e7-8b49-635f2513e4b9.png)

**Comment by markhaines** [comment] 2017-09-06 15:17
What does your advanced.yaml config file look like?  I customised the .example one on mine and renamed it as it was notated better in case I needed to change it in the future.

**Comment by madvtak** [comment] 2017-09-06 15:20
I havnet touched my advanced.yaml, this could be why.

**Comment by markhaines** [comment] 2017-09-06 15:20
Yep, that'll do it ;-)

**Comment by ninthwalker** [comment] 2017-09-06 15:23
Thanks for helping him out Mark. 
His files/config may be fine.

The command line to test/run manually is wrong. 
It should look like this:

docker exec name_you_gave_docker nowshowing webreport

**Comment by madvtak** [comment] 2017-09-06 15:26
@markhaines do you mind sharing your yaml file. I am not sure what needs to be changed here.

@ninthwalker when i run your command i still get config file not found. 

![image](https://user-images.githubusercontent.com/18261123/30120193-0517d4f6-92dd-11e7-89e3-ca42ae230b0a.png)

**Comment by madvtak** [comment] 2017-09-06 16:56
Okay i have narrowed down the issue to, it cannot see the config file? 

![image](https://user-images.githubusercontent.com/18261123/30124339-b0ecf976-92e9-11e7-9a09-766b48d97f99.png)

**Comment by madvtak** [comment] 2017-09-06 21:41
Sorry to be such a bother, i found something else. When i look at logs in Docker it shows a config file, but i dont know how to get to it to edit it.

![image](https://user-images.githubusercontent.com/18261123/30135845-6986e1fa-9311-11e7-8094-17598e290c22.png)

**Comment by madvtak** [comment] 2017-09-06 21:51
How do i get into here and just edit??

![image](https://user-images.githubusercontent.com/18261123/30136241-e2ea928e-9312-11e7-8059-e930e36b94d2.png)

**Comment by madvtak** [comment] 2017-09-06 21:53
I see these, but how do i get in here???

![image](https://user-images.githubusercontent.com/18261123/30136291-267cf1ea-9313-11e7-9ae0-9901ba95542c.png)

**Comment by madvtak** [comment] 2017-09-06 22:04
I see this from [here](https://forums.lime-technology.com/topic/56483-support-ninthwalker-nowshowing/) but mine doesn't have a config.yaml

[docker exec nowshowing cat /opt/config.yaml](url)

**Comment by madvtak** [comment] 2017-09-08 23:10
@markhaines do you mind sharing your Environment Variables also please?

**Comment by ninthwalker** [comment] 2017-09-16 20:08
Someone else other than me will have to finish helping you as I do not have a Synology or know how they setup their docker environment. Only have experience with Docker on Linux and unRAID systems. Good luck!

**Comment by markhaines** [comment] 2017-09-17 16:53
Here's my docker settings within DSM:
<img width="1012" alt="ds2 nas 2" src="https://user-images.githubusercontent.com/1022008/30523002-18f0c4b8-9bd1-11e7-9b05-32dbb3aa2632.png">
<img width="1012" alt="ds2 nas" src="https://user-images.githubusercontent.com/1022008/30523003-18f18cea-9bd1-11e7-90e3-ae9d8472605b.png">

**Comment by markhaines** [comment] 2017-09-17 16:56
Not sure if there's anything else useful I can share with you - it 'just works' for me!

**Comment by markhaines** [comment] 2017-09-17 17:11
<img width="717" alt="ds2 nas" src="https://user-images.githubusercontent.com/1022008/30523126-7db0c482-9bd3-11e7-9996-5f28c2298fac.png">
This is the command I run (having first ssh'd into the DSM as root) from the shell.  This updates the webpage and sends out a test email.

**Comment by markhaines** [comment] 2017-09-17 17:21
I tried "docker exec nowshowing cat /opt/config.yaml" and it displays a list of the environment variables configured within the DSM Docker UI.  So if you don't have that working then that's probably the starting point.

**Comment by ninthwalker** [comment] 2017-10-09 19:55
Closing this for now, as it's not a bug but a configuration setup within DSM. Since Markhaines has it working you could possibly get more help from him via PM. Thanks.

**Closed by ninthwalker** 2017-10-09 19:55 UTC
